name: Test

on:
  workflow_dispatch:

jobs:
  test:
    uses: juancamilo-nb/public-action/.github/workflows/public.yml@master
    with:
      username: "juan"
      image: "test.png"
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
