name: Test

on:
  workflow_dispatch:

jobs:
  call-public:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger public workflow
        uses: juancamilo-nb/publicado@v1
        with: 
          username: "pancracio"
          image: "tarcicio.png"
